<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>All_in_One</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Configurations>Debug;Release;DKP_Requirement;NewLootSystem;OpenDKPSystem</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SchwarzerDrachenschwarmLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Cells" Version="23.1.1" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.61.0.3113" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="SchwarzerDrachenschwarmLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Static\Extern Data\dkp-evershire-rids-9397f0d50e94.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Static\Extern Data\SchwarzerDrachenschwarmLogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
