using System.Collections.Generic;

namespace All_in_One.DataModels.DKPModels
{
    internal class Enchantments
    {
        /// <summary>
        /// Liste aller Verzauberungen. Einige Verzauberungen betreffen mehrere Stats.
        /// </summary>
        public static List<Enchantment> AcceptedEnchantments = new List<Enchantment>()
        {
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Angriffstempo,1,true)},2543),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Mana,150)},1483),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausweichen,1,true)},2545),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,8)},2544),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Gesundheit,100)},1503),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Beweglichkeit,8)},1508),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Intelligenz,8)},1509),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Stärke,8)},1506),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Willenskraft,8)},1510),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,8)},1507),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,18),new EnchantmentBaseClass(EnchantmentStat.Zaubertrefferchance,1,true)},2588),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,10),new EnchantmentBaseClass(EnchantmentStat.Intelligenz,10), new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,24)},2591),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,10),new EnchantmentBaseClass(EnchantmentStat.Verteidigung,7), new EnchantmentBaseClass(EnchantmentStat.Schildblockwert,15)},2583),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,10),new EnchantmentBaseClass(EnchantmentStat.Manaregeneration,4), new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,24)},2590),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,10),new EnchantmentBaseClass(EnchantmentStat.Distanzangriffskraft,24), new EnchantmentBaseClass(EnchantmentStat.Trefferchance,1,true)},2586),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,10),new EnchantmentBaseClass(EnchantmentStat.Verteidigung,7), new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,24)},2584),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Angriffskraft,28),new EnchantmentBaseClass(EnchantmentStat.Ausweichen,1,true)},2585),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,10),new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,18)},2589),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Feuerwiderstand,5)},2483),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Frostwiderstand,5)},2484),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Arkanwiderstand,5)},2485),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Naturwiderstand,5)},2486),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Angriffskraft,30)},2606),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,18)},2605),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,33)},2604),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Verteidigung,3)},2503),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Rüstung,70)},1889),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Werte,4)},1891),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Werte,3)},928),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausweichen,1,true)},2622),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Bedrohungsverringerung,2,true)},2621),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Alle_Widerstände,5)},1888),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Beweglichkeit,3)},849),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,24)},2566),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,9)},1886),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Stärke,9)},1885),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Willenskraft,9)},1884),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Intelligenz,7)},1883),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Beweglichkeit,15)},2564),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,20)},2614),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,20)},2615),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,20)},2616),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,30)},2617),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Stärke,7)},927),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Beweglichkeit,7)},1887),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Willenskraft,5)},851),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,7)},929),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Beweglichkeit,7)},1887),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Sonstiges,0)},911),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Manaregeneration,4)},2565),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Mana,100)},1893),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Gesundheit,100)},1892),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Verteidigung,3)},923),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Feuerwiderstand,15)},2619),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Naturwiderstand,15)},2620),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Schattenwiderstand,10)},804),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Intelligenz,22)},2568),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Willenskraft,20)},2567),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Sonstiges,0)},1900),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,30)},2504),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,55)},2505),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Waffenschaden,5)},804),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Sonstiges,0)},1898),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Sonstiges,2,true)},863), //geringes blocken
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Stärke,15)},2563),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Beweglichkeit,15)},2564),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Sonstiges,0)},803),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,7)},2443),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Willenskraft,9)},1903),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Waffenschaden,9)},1896),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Intelligenz,9)},1904),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Beweglichkeit,25)},2646),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Waffenschaden,7)},664),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Waffenschaden,1)},30),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Waffenschaden,2)},32),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Waffenschaden,5)},663),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Trefferchance,3,true)},2523),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Naturwiderstand,10)},2681),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Schattenwiderstand,10)},2683),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Schattenwiderstand,5)},2487),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Naturwiderstand,5)},2486),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Feuerwiderstand,5)},2483),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Frostwiderstand,5)},2484),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Feuerwiderstand,20)},1505),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Sonstiges,0)},2613),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Nahkampftempo,1,true)},931),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Sonstiges,0)},1704),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Ausdauer,16),new EnchantmentBaseClass(EnchantmentStat.Rüstung,100)},2716),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Zauberschaden,15),new EnchantmentBaseClass(EnchantmentStat.Zaubercrit,1,true)},2721),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Heilungsbonus,31),new EnchantmentBaseClass(EnchantmentStat.Manaregeneration,5)},2715),
            new Enchantment(new List<EnchantmentBaseClass>(){new EnchantmentBaseClass(EnchantmentStat.Angriffskraft,26),new EnchantmentBaseClass(EnchantmentStat.Nahkampfcrit,1,true)},2721),
        };
        public enum EnchantmentStat
        {
            Angriffstempo,
            Mana,
            Ausweichen,
            Zauberschaden,
            Gesundheit,
            Beweglichkeit,
            Intelligenz,
            Willenskraft,
            Stärke,
            Ausdauer,
            Zaubertrefferchance,
            Verteidigung,
            Schildblockwert,
            Heilungsbonus,
            Angriffskraft,
            Distanzangriffskraft,
            Werte,
            Feuerwiderstand,
            Frostwiderstand,
            Naturwiderstand,
            Schattenwiderstand,
            Arkanwiderstand,
            Manaregeneration,
            Trefferchance,
            Bedrohungsverringerung,
            Alle_Widerstände,
            Sonstiges,
            Waffenschaden,
            Mp5,
            Rüstung,
            Zaubercrit,
            Nahkampfcrit,
            Nahkampftempo,
        }

    }
}
